<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_successPickCategory</name>
   <tag></tag>
   <elementGuidId>5b0db1cd-d1bc-4aba-8557-18e5b32590db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='css-1dq1dix']//div[contains(text(), 'Menampilkan')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1dq1dix > div > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4419e2e2-dcfc-48f3-9e74-18a01707ba1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menampilkan 325461 produk untuk  &quot;Baterai &amp; Charger Kamera&quot;  (1 - 60 of  325461)</value>
      <webElementGuid>860841bc-2def-4b84-907b-dcaaf4c0428f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[2]/div[@class=&quot;css-gvsi1m e1nlzfl0&quot;]/div[@class=&quot;css-1xpribl e1nlzfl3&quot;]/div[@class=&quot;css-1mvy9n0 e1nlzfl4&quot;]/div[@class=&quot;css-18p2ktc&quot;]/div[@class=&quot;css-13wayc1&quot;]/div[@class=&quot;css-1dq1dix&quot;]/div[1]/div[1]</value>
      <webElementGuid>9a510145-1c03-4759-86a4-4bfa5207a206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div/div[2]/div[3]/div[2]/div/div</value>
      <webElementGuid>34b88e18-aac0-4a93-8ddc-32387c2440d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/following::div[3]</value>
      <webElementGuid>fc120ade-fd9c-40ac-9eb7-687121d90511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp154.500'])[1]/following::div[4]</value>
      <webElementGuid>b8f1f4e8-7836-407b-b8c0-f644e7322654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah ke Wishlist'])[1]/preceding::div[2]</value>
      <webElementGuid>c0c5db1c-a2b6-4bdd-8f0f-f35cc37b6cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menampilkan']/parent::*</value>
      <webElementGuid>454757a4-96a5-4e8d-8b4b-5b724c920086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div</value>
      <webElementGuid>bbe19a0f-9a07-4ea1-a40b-ab6515fa6e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Menampilkan 325461 produk untuk  &quot;Baterai &amp; Charger Kamera&quot;  (1 - 60 of  325461)' or . = 'Menampilkan 325461 produk untuk  &quot;Baterai &amp; Charger Kamera&quot;  (1 - 60 of  325461)')]</value>
      <webElementGuid>767d9ccf-6d6a-4d88-8f06-a1da9e852929</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
