<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_selectChildCategories</name>
   <tag></tag>
   <elementGuidId>f0cca21e-f005-489a-aaed-2722f9eaed08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '/p/rumah-tangga/dekorasi/cover-kipas-angin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96b26716-b90e-47fa-8e73-afb723bf414e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>categoryNavigation#1</value>
      <webElementGuid>afcf5082-c2fb-4833-b6f9-59e4459209f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/p/rumah-tangga/dekorasi/cover-kipas-angin</value>
      <webElementGuid>b130ba26-3bb9-46bb-999b-72080f9debec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-ges1q2</value>
      <webElementGuid>627cd5e3-a658-4a5a-91f8-d34707e32917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cover Kipas Angin</value>
      <webElementGuid>5f3ca685-bd00-4779-8b0f-e6b9056fadb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;css-32o8lv e1429ojz2&quot;]/div[@class=&quot;css-11womkr-unf-tab e1429ojz3&quot;]/div[@class=&quot;css-dj3o3l&quot;]/div[@class=&quot;css-1iefgdn e1429ojz5&quot;]/div[@class=&quot;css-113hzvq&quot;]/div[@class=&quot;css-11p7ov6&quot;]/div[@class=&quot;css-s0g7na&quot;]/div[@class=&quot;css-1owj1eu&quot;]/div[@class=&quot;css-bfgk5q&quot;]/a[@class=&quot;css-ges1q2&quot;]</value>
      <webElementGuid>e59e206b-9ee7-4386-a9eb-94da4c30c9d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/p/rumah-tangga/dekorasi/cover-kipas-angin' and (text() = 'Cover Kipas Angin' or . = 'Cover Kipas Angin')]</value>
      <webElementGuid>a1f758e1-1e50-481d-9091-bbe48daacfc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
