<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_checkHoverCategories</name>
   <tag></tag>
   <elementGuidId>82a31b4a-66de-4274-809e-772ec1549b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-testid='allCategories']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5522f628-5ba1-471a-8786-195920ef0893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>allCategories</value>
      <webElementGuid>6514545e-f23e-4bfb-b906-bdae51b6ca10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-103qbjm e1429ojz4</value>
      <webElementGuid>2bff0f69-5d68-4d1a-99d1-b3e705b12052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rumah TanggaAudio, Kamera &amp; Elektronik LainnyaBukuDapurElektronikFashion Anak &amp; BayiFashion MuslimFashion PriaFashion WanitaFilm &amp; MusikGamingHandphone &amp; TabletIbu &amp; BayiKecantikanKesehatanKomputer &amp; LaptopLogam MuliaMainan &amp; HobiMakanan &amp; MinumanOffice &amp; StationeryOlahragaOtomotifPerawatan HewanPerawatan TubuhPerlengkapan PestaPertukanganPropertiTiket, Travel, Voucher</value>
      <webElementGuid>ff41b5a9-50c6-4ac7-a5a6-566cea234f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;css-32o8lv e1429ojz2&quot;]/div[@class=&quot;css-11womkr-unf-tab e1429ojz3&quot;]/div[@class=&quot;css-dj3o3l&quot;]/div[@class=&quot;css-103qbjm e1429ojz4&quot;]</value>
      <webElementGuid>6e967473-ee4b-4943-9789-acda3b546a8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rumah TanggaAudio, Kamera &amp; Elektronik LainnyaBukuDapurElektronikFashion Anak &amp; BayiFashion MuslimFashion PriaFashion WanitaFilm &amp; MusikGamingHandphone &amp; TabletIbu &amp; BayiKecantikanKesehatanKomputer &amp; LaptopLogam MuliaMainan &amp; HobiMakanan &amp; MinumanOffice &amp; StationeryOlahragaOtomotifPerawatan HewanPerawatan TubuhPerlengkapan PestaPertukanganPropertiTiket, Travel, Voucher' or . = 'Rumah TanggaAudio, Kamera &amp; Elektronik LainnyaBukuDapurElektronikFashion Anak &amp; BayiFashion MuslimFashion PriaFashion WanitaFilm &amp; MusikGamingHandphone &amp; TabletIbu &amp; BayiKecantikanKesehatanKomputer &amp; LaptopLogam MuliaMainan &amp; HobiMakanan &amp; MinumanOffice &amp; StationeryOlahragaOtomotifPerawatan HewanPerawatan TubuhPerlengkapan PestaPertukanganPropertiTiket, Travel, Voucher')]</value>
      <webElementGuid>bbed2b75-8ce5-4ad4-b47d-28c4b52016a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
