<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dynamic_homepageCategory</name>
   <tag></tag>
   <elementGuidId>9a094a14-7b92-4dbb-9e00-4fa08c55a592</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Kategori' or . = 'Kategori')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='css-1ukamyt']//a[@data-testid='${DATA_TEST_ID}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-1g2ipts</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a49a3ac-e1c6-4562-9296-d8864ae210ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.tokopedia.com/p?nref=chead&amp;source=homepage.dynamic_icon.0.824</value>
      <webElementGuid>b2660912-15c0-4130-9aa1-729e284f3a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1g2ipts</value>
      <webElementGuid>e81e124c-11b1-4d71-9ebd-add5372ae3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b9a49c92-61f4-41b4-afd6-9b0005a24edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a72351e-daad-4947-a1b5-35432f1332a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>icnHomeDynamicIcon#1</value>
      <webElementGuid>4b4a38f6-0ec6-4861-accc-52d16db86ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori</value>
      <webElementGuid>a6bec6d9-8824-4e92-b349-3fbc658a7b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/main[@class=&quot;css-15x0u31&quot;]/section[@class=&quot;css-stopwq bordered&quot;]/div[@class=&quot;css-3kh9t4&quot;]/div[@class=&quot;css-1ukamyt&quot;]/div[@class=&quot;css-1cysb4j&quot;]/div[@class=&quot;css-1jke4yk&quot;]/div[@class=&quot;css-1995st&quot;]/a[@class=&quot;css-1g2ipts&quot;]</value>
      <webElementGuid>97fe9399-b453-4025-af8d-d380e8be1e6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/section/div/div[2]/div/div/div/a</value>
      <webElementGuid>3e6d4c0a-edd6-4c5c-b0e5-f77b362bb1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli'])[1]/following::a[1]</value>
      <webElementGuid>bd7f938c-fff4-4baa-9391-14b81e3d0350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nominal'])[1]/following::a[1]</value>
      <webElementGuid>3f35bc63-828e-4f9f-b95c-300c09466fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Handphone &amp; Tablet'])[1]/preceding::a[1]</value>
      <webElementGuid>a6f017fe-fb95-4831-8426-918d2bdb3180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.tokopedia.com/p?nref=chead&amp;source=homepage.dynamic_icon.0.824')]</value>
      <webElementGuid>4cb6d33d-638f-4517-b99e-f6555d47deb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>4ec66999-2462-4531-8ef8-56c894808b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.tokopedia.com/p?nref=chead&amp;source=homepage.dynamic_icon.0.824' and (text() = 'Kategori' or . = 'Kategori')]</value>
      <webElementGuid>0047cc0f-b62f-4555-87cf-930226b8cb90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
