<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_selectChildCategories</name>
   <tag></tag>
   <elementGuidId>f0cca21e-f005-489a-aaed-2722f9eaed08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '/p/${SELECTED_CHILD_CATEGORY}']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6df88683-9246-4056-a60f-ba0b27a21fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>categoryNavigation#1</value>
      <webElementGuid>d25f5a84-b44b-4c71-96b5-e299481c7ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/p/rumah-tangga/dekorasi/cover-kipas-angin</value>
      <webElementGuid>bc902032-bee1-4dea-92ef-e26d0dea1c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-ges1q2</value>
      <webElementGuid>dd728770-972a-4090-b8af-89d625b1bc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cover Kipas Angin</value>
      <webElementGuid>9b62f5dd-83be-4b8e-a986-d45063750d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;css-32o8lv e1429ojz2&quot;]/div[@class=&quot;css-11womkr-unf-tab e1429ojz3&quot;]/div[@class=&quot;css-dj3o3l&quot;]/div[@class=&quot;css-1iefgdn e1429ojz5&quot;]/div[@class=&quot;css-113hzvq&quot;]/div[@class=&quot;css-11p7ov6&quot;]/div[@class=&quot;css-s0g7na&quot;]/div[@class=&quot;css-1owj1eu&quot;]/div[@class=&quot;css-bfgk5q&quot;]/a[@class=&quot;css-ges1q2&quot;]</value>
      <webElementGuid>72dc6236-d185-4353-a29a-d54edb6c44c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/p/rumah-tangga/dekorasi/cover-kipas-angin' and (text() = 'Cover Kipas Angin' or . = 'Cover Kipas Angin')]</value>
      <webElementGuid>b8938ad3-bdf9-4d22-9798-740136272f13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
