<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_span_Penawaran</name>
   <tag></tag>
   <elementGuidId>711d2db7-11dc-49ad-8ff0-49ff22a9e0c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='css-1cb34wj']//span[contains(text(),'COD')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>4cecac85-30b9-44d5-993f-a6e0681b1ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1737439128136</value>
      <webElementGuid>e82a705d-cf60-4f67-a14a-07861999ddfc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
