<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_span_Rating</name>
   <tag></tag>
   <elementGuidId>64ac8b9c-8d57-41c7-b8f5-d4b9f8788c83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Rating 4 ke atas')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>078aeeb9-ff4b-4543-a2a4-95b4d3dddb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1737434129138</value>
      <webElementGuid>accaa5e0-253c-458d-a71f-cdf027e2f37d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
