<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_span_JenisToko</name>
   <tag></tag>
   <elementGuidId>0bd9b5cb-5a3d-4c0b-8479-0896ca754281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//label[span[text()='${JENIS_TOKO}']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>8214a557-bf46-469c-a662-c81ea0417ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1737389492204</value>
      <webElementGuid>d087a3c1-c62e-4b9d-99ff-3c5ee101729c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
