<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_span_Kondisi</name>
   <tag></tag>
   <elementGuidId>ab5f750d-2ad7-485a-aa38-17e9ac0c93cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-testid='dSRPCondFilter']//*//span[contains(text(),'${xKONDISI}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>4c31c433-9041-482c-a270-faa51c349821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1737433979256</value>
      <webElementGuid>b87800c2-e462-4fcb-80a0-6ea2bef43c44</webElementGuid>
   </webElementProperties>
</WebElementEntity>
