<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_span_Penawaran</name>
   <tag></tag>
   <elementGuidId>711d2db7-11dc-49ad-8ff0-49ff22a9e0c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='css-1cb34wj']//span[contains(text(),'${xPENAWARAN}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>538c5e49-56e8-499c-9c23-1820580a6fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1737439128136</value>
      <webElementGuid>fb18348d-b5bb-418f-bac6-0cd612b8efc1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
