<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_invalidCredentials</name>
   <tag></tag>
   <elementGuidId>b7169a7a-722e-48a1-9ab3-3af8e02d0ef0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@class='oxd-text oxd-text--p oxd-alert-content-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>67056dd6-b927-499c-9083-d870a07a0407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1740305953065</value>
      <webElementGuid>d4a37c1d-611a-42b2-995d-ab0f71df9437</webElementGuid>
   </webElementProperties>
</WebElementEntity>
