<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_headerProfile</name>
   <tag></tag>
   <elementGuidId>bd80a7c4-54a5-47e6-bc7a-6b8ae375ed3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='oxd-userdropdown-tab']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>12f1da2e-40bf-4e36-9809-f213a46c51b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1740307912759</value>
      <webElementGuid>a57aa88c-c194-46ab-ba69-d941ad8a7225</webElementGuid>
   </webElementProperties>
</WebElementEntity>
